<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEK0OYDo\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEK0OYDo/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEK0OYDo.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEK0OYDo\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerEK0OYDo\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'EK0OYDo',
    'container.build_id' => '4bb91e30',
    'container.build_time' => 1645032229,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEK0OYDo');
